# Generated by Django 5.2.3 on 2025-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_number', models.CharField(blank=True, help_text='e.g., +234 801 234 5678', max_length=20)),
                ('secondary_phone_number', models.CharField(blank=True, help_text='Optional second contact number', max_length=20)),
                ('primary_whatsapp_number', models.CharField(blank=True, help_text="WhatsApp number including country code, e.g., 2348012345678 (no '+')", max_length=20)),
                ('primary_email', models.EmailField(blank=True, help_text='Main contact/support email address', max_length=254)),
                ('office_address', models.TextField(blank=True, help_text='Full office address, use line breaks for formatting.')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True, help_text='URL for your X (formerly Twitter) profile')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('color_brand_primary', models.CharField(default='#1993e5', help_text='Primary brand color (e.g., buttons, accents)', max_length=7)),
                ('color_brand_secondary', models.CharField(default='#111518', help_text='Secondary color (e.g., dark text, headings)', max_length=7)),
                ('footer_copyright_text', models.CharField(blank=True, default='Nairaxi Car Leasing. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
