# Generated by Django 5.2.3 on 2025-07-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone_number',
            field=models.CharField(blank=True, help_text='e.g., +234 915 5541 159', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_whatsapp_number',
            field=models.CharField(blank=True, help_text="WhatsApp number including country code, e.g., 2349155541159 (no '+')", max_length=20),
        ),
    ]
