# Generated by Django 5.2.3 on 2025-07-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('drivers_license', models.FileField(upload_to='lease_documents/licenses/%Y/%m/')),
                ('identification_document', models.FileField(upload_to='lease_documents/ids/%Y/%m/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Lease Active'), ('Completed', 'Lease Completed')], default='Pending', max_length=20)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('initial_payment_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_applications', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_applications', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('paystack_charge_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leasing.leaseapplication')),
            ],
        ),
    ]
